### ISSUE TITLE
不采用npm安装，使用传统引入方式该怎么使用？

### ISSUE THREAD

**Issue by devotion987** [luosijie/vm-markdown#6]
不采用npm安装，使用传统引入方式该怎么使用？

**Comment by luosijie** [comment]
1.把项目下载到本地
2.复制src的文件到自己的项目
3.安装好依赖项
4.在自己的项目引入vm-markdown.vue

**Comment by devotion987** [comment]
直接引入vm_markdown.min.js不行吗？

**Comment by luosijie** [comment]
也行，直接引入和用npm安装没有区别

**Comment by devotion987** [comment]
我的代码这么写的，该怎么将这个组件引入？
`var articleVue = new Vue({
    el: '#blue_article',
    data: {
        q: {
            articleTitle: null
        },
        showList: true,
        article: {
            title: null,
            tags: null,
            content: null
        }
    },
    components: {
        VmMarkdown
    },
    methods: {
        query: function () {
        },
        add: function () {
            articleVue.showList = false;
            articleVue.title = "新增";
        },
        update: function () {
        },
        del: function () {
        },
        subArticle : function (status) {
            alert(status)
        },
        showHtml : function () {
            
        }
    }
});`

**Comment by luosijie** [comment]
模式不一样，我要想想怎么解决

**Comment by devotion987** [comment]
好的，解决好了麻烦通知下，刚好可以用到项目里

**Comment by luosijie** [comment]
这是Demo，也可以直接引用vm_markdown.min.js

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script type="text/javascript" src="http://vuejs.org/js/vue.min.js"></script>
	<script type="text/javascript" src="https://unpkg.com/vm-markdown"></script>
</head>
<body>
<div id="app">
	<vm-markdown theme="princess" v-on:gethtml="showHtml"></vm-markdown>
</div>
<script>
	new Vue({
        el: '#app',
        data: {
            show: 'Hello Vue'
        },
        methods: {
            showHtml: function(html) {
              console.log(html)
		    }
        }
    })
</script>
</body>
</html>

**Comment by devotion987** [comment]
试了下，可以用，感谢！

**Comment by devotion987** [comment]
想改造图片上传，可选择从本地选择图片，图片上传对应的api什么？

**Comment by luosijie** [comment]
目前没有开放本地图片上传的功能
